

package com.smm.ctrm.domain.Basis;
// default package
// Generated 2016-4-20 21:28:15 by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * RoleMenuId generated by hbm2java
 */
@Embeddable
public class RoleMenuId implements java.io.Serializable {

	@JsonProperty(value = "RoleId")
	private String roleId;
	@JsonProperty(value = "Id")
	private String id;
	@JsonProperty(value = "Version")
	private Integer version;
	@JsonProperty(value = "Instance")
	private Serializable instance;
	@JsonProperty(value = "IsDeleted")
	private Boolean isDeleted;
	@JsonProperty(value = "IsHidden")
	private Boolean isHidden;
	@JsonProperty(value = "CreatedBy")
	private Serializable createdBy;
	@JsonProperty(value = "CreatedAt")
	private Date createdAt;
	@JsonProperty(value = "UpdatedBy")
	private Serializable updatedBy;
	@JsonProperty(value = "UpdatedAt")
	private Date updatedAt;
	@JsonProperty(value = "DeletedBy")
	private Serializable deletedBy;
	@JsonProperty(value = "DeletedAt")
	private Date deletedAt;
	@JsonProperty(value = "ButtonId")
	private String buttonId;
	@JsonProperty(value = "ResourceId")
	private String resourceId;
	@JsonProperty(value = "MenuId")
	private String menuId;


	public RoleMenuId() {
	}

	public RoleMenuId(String roleId) {
		this.roleId = roleId;
	}

	public RoleMenuId(String roleId, String id, Integer version,
			Serializable instance, Boolean isDeleted, Boolean isHidden,
			Serializable createdBy, Date createdAt, Serializable updatedBy,
			Date updatedAt, Serializable deletedBy, Date deletedAt,
			String buttonId, String resourceId, String menuId) {
		this.roleId = roleId;
		this.id = id;
		this.version = version;
		this.instance = instance;
		this.isDeleted = isDeleted;
		this.isHidden = isHidden;
		this.createdBy = createdBy;
		this.createdAt = createdAt;
		this.updatedBy = updatedBy;
		this.updatedAt = updatedAt;
		this.deletedBy = deletedBy;
		this.deletedAt = deletedAt;
		this.buttonId = buttonId;
		this.resourceId = resourceId;
		this.menuId = menuId;
	}

	@Column(name = "RoleId", nullable = false, length = 36)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "Id", length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "Version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@Column(name = "Instance")
	public Serializable getInstance() {
		return this.instance;
	}

	public void setInstance(Serializable instance) {
		this.instance = instance;
	}

	@Column(name = "IsDeleted")
	public Boolean getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(Boolean isDeleted) {
		this.isDeleted = isDeleted;
	}

	@Column(name = "IsHidden")
	public Boolean getIsHidden() {
		return this.isHidden;
	}

	public void setIsHidden(Boolean isHidden) {
		this.isHidden = isHidden;
	}

	@Column(name = "CreatedBy")
	public Serializable getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(Serializable createdBy) {
		this.createdBy = createdBy;
	}

	@Column(name = "CreatedAt", length = 23)
	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	@Column(name = "UpdatedBy")
	public Serializable getUpdatedBy() {
		return this.updatedBy;
	}

	public void setUpdatedBy(Serializable updatedBy) {
		this.updatedBy = updatedBy;
	}

	@Column(name = "UpdatedAt", length = 23)
	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	@Column(name = "DeletedBy")
	public Serializable getDeletedBy() {
		return this.deletedBy;
	}

	public void setDeletedBy(Serializable deletedBy) {
		this.deletedBy = deletedBy;
	}

	@Column(name = "DeletedAt", length = 23)
	public Date getDeletedAt() {
		return this.deletedAt;
	}

	public void setDeletedAt(Date deletedAt) {
		this.deletedAt = deletedAt;
	}

	@Column(name = "ButtonId", length = 36)
	public String getButtonId() {
		return this.buttonId;
	}

	public void setButtonId(String buttonId) {
		this.buttonId = buttonId;
	}

	@Column(name = "ResourceId", length = 36)
	public String getResourceId() {
		return this.resourceId;
	}

	public void setResourceId(String resourceId) {
		this.resourceId = resourceId;
	}

	@Column(name = "MenuId", length = 36)
	public String getMenuId() {
		return this.menuId;
	}

	public void setMenuId(String menuId) {
		this.menuId = menuId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof RoleMenuId))
			return false;
		RoleMenuId castOther = (RoleMenuId) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this
				.getRoleId() != null && castOther.getRoleId() != null && this
				.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getId() == castOther.getId()) || (this.getId() != null
						&& castOther.getId() != null && this.getId().equals(
						castOther.getId())))
				&& ((this.getVersion() == castOther.getVersion()) || (this
						.getVersion() != null && castOther.getVersion() != null && this
						.getVersion().equals(castOther.getVersion())))
				&& ((this.getInstance() == castOther.getInstance()) || (this
						.getInstance() != null
						&& castOther.getInstance() != null && this
						.getInstance().equals(castOther.getInstance())))
				&& ((this.getIsDeleted() == castOther.getIsDeleted()) || (this
						.getIsDeleted() != null
						&& castOther.getIsDeleted() != null && this
						.getIsDeleted().equals(castOther.getIsDeleted())))
				&& ((this.getIsHidden() == castOther.getIsHidden()) || (this
						.getIsHidden() != null
						&& castOther.getIsHidden() != null && this
						.getIsHidden().equals(castOther.getIsHidden())))
				&& ((this.getCreatedBy() == castOther.getCreatedBy()) || (this
						.getCreatedBy() != null
						&& castOther.getCreatedBy() != null && this
						.getCreatedBy().equals(castOther.getCreatedBy())))
				&& ((this.getCreatedAt() == castOther.getCreatedAt()) || (this
						.getCreatedAt() != null
						&& castOther.getCreatedAt() != null && this
						.getCreatedAt().equals(castOther.getCreatedAt())))
				&& ((this.getUpdatedBy() == castOther.getUpdatedBy()) || (this
						.getUpdatedBy() != null
						&& castOther.getUpdatedBy() != null && this
						.getUpdatedBy().equals(castOther.getUpdatedBy())))
				&& ((this.getUpdatedAt() == castOther.getUpdatedAt()) || (this
						.getUpdatedAt() != null
						&& castOther.getUpdatedAt() != null && this
						.getUpdatedAt().equals(castOther.getUpdatedAt())))
				&& ((this.getDeletedBy() == castOther.getDeletedBy()) || (this
						.getDeletedBy() != null
						&& castOther.getDeletedBy() != null && this
						.getDeletedBy().equals(castOther.getDeletedBy())))
				&& ((this.getDeletedAt() == castOther.getDeletedAt()) || (this
						.getDeletedAt() != null
						&& castOther.getDeletedAt() != null && this
						.getDeletedAt().equals(castOther.getDeletedAt())))
				&& ((this.getButtonId() == castOther.getButtonId()) || (this
						.getButtonId() != null
						&& castOther.getButtonId() != null && this
						.getButtonId().equals(castOther.getButtonId())))
				&& ((this.getResourceId() == castOther.getResourceId()) || (this
						.getResourceId() != null
						&& castOther.getResourceId() != null && this
						.getResourceId().equals(castOther.getResourceId())))
				&& ((this.getMenuId() == castOther.getMenuId()) || (this
						.getMenuId() != null && castOther.getMenuId() != null && this
						.getMenuId().equals(castOther.getMenuId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getVersion() == null ? 0 : this.getVersion().hashCode());
		result = 37 * result
				+ (getInstance() == null ? 0 : this.getInstance().hashCode());
		result = 37 * result
				+ (getIsDeleted() == null ? 0 : this.getIsDeleted().hashCode());
		result = 37 * result
				+ (getIsHidden() == null ? 0 : this.getIsHidden().hashCode());
		result = 37 * result
				+ (getCreatedBy() == null ? 0 : this.getCreatedBy().hashCode());
		result = 37 * result
				+ (getCreatedAt() == null ? 0 : this.getCreatedAt().hashCode());
		result = 37 * result
				+ (getUpdatedBy() == null ? 0 : this.getUpdatedBy().hashCode());
		result = 37 * result
				+ (getUpdatedAt() == null ? 0 : this.getUpdatedAt().hashCode());
		result = 37 * result
				+ (getDeletedBy() == null ? 0 : this.getDeletedBy().hashCode());
		result = 37 * result
				+ (getDeletedAt() == null ? 0 : this.getDeletedAt().hashCode());
		result = 37 * result
				+ (getButtonId() == null ? 0 : this.getButtonId().hashCode());
		result = 37
				* result
				+ (getResourceId() == null ? 0 : this.getResourceId()
						.hashCode());
		result = 37 * result
				+ (getMenuId() == null ? 0 : this.getMenuId().hashCode());
		return result;
	}

}