

package com.smm.ctrm.domain.Basis;
// default package
// Generated 2016-4-20 21:28:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SysSequenceResult generated by hbm2java
 */
@Entity
@Table(name = "SYS_SEQUENCE_RESULT", schema = "Basis")
public class SysSequenceResult implements java.io.Serializable {

	private SysSequenceResultId id;
	@JsonProperty(value = "Confirmed")
	private Boolean confirmed;

	public SysSequenceResult() {
	}

	public SysSequenceResult(SysSequenceResultId id) {
		this.id = id;
	}

	public SysSequenceResult(SysSequenceResultId id, Boolean confirmed) {
		this.id = id;
		this.confirmed = confirmed;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "code", column = @Column(name = "CODE", nullable = false, length = 200)),
			@AttributeOverride(name = "lastid", column = @Column(name = "LASTID", nullable = false, precision = 18, scale = 0)) })
	public SysSequenceResultId getId() {
		return this.id;
	}

	public void setId(SysSequenceResultId id) {
		this.id = id;
	}

	@Column(name = "Confirmed")
	public Boolean getConfirmed() {
		return this.confirmed;
	}

	public void setConfirmed(Boolean confirmed) {
		this.confirmed = confirmed;
	}

}