

package com.smm.ctrm.domain.Basis;
// default package
// Generated 2016-4-20 21:28:15 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SysSequenceResultId generated by hbm2java
 */
@Embeddable
public class SysSequenceResultId implements java.io.Serializable {

	@JsonProperty(value = "Code")
	private String code;
	@JsonProperty(value = "Lastid")
	private long lastid;

	public SysSequenceResultId() {
	}

	public SysSequenceResultId(String code, long lastid) {
		this.code = code;
		this.lastid = lastid;
	}

	@Column(name = "CODE", nullable = false, length = 200)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "LASTID", nullable = false, precision = 18, scale = 0)
	public long getLastid() {
		return this.lastid;
	}

	public void setLastid(long lastid) {
		this.lastid = lastid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SysSequenceResultId))
			return false;
		SysSequenceResultId castOther = (SysSequenceResultId) other;

		return ((this.getCode() == castOther.getCode()) || (this.getCode() != null
				&& castOther.getCode() != null && this.getCode().equals(
				castOther.getCode())))
				&& (this.getLastid() == castOther.getLastid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getCode() == null ? 0 : this.getCode().hashCode());
		result = 37 * result + (int) this.getLastid();
		return result;
	}

}