
package com.smm.ctrm.domain.Physical;
// default package

// Generated 2016-4-20 21:35:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * InvoiceNoticeId generated by hbm2java
 */
@Embeddable
public class InvoiceNoticeId implements java.io.Serializable {

	@JsonProperty(value = "InvoiceId")
	private String invoiceId;
	@JsonProperty(value = "StorageId")
	private String storageId;

	public InvoiceNoticeId() {
	}

	public InvoiceNoticeId(String invoiceId, String storageId) {
		this.invoiceId = invoiceId;
		this.storageId = storageId;
	}

	@Column(name = "InvoiceId", nullable = false, length = 36)
	public String getInvoiceId() {
		return this.invoiceId;
	}

	public void setInvoiceId(String invoiceId) {
		this.invoiceId = invoiceId;
	}

	@Column(name = "StorageId", nullable = false, length = 36)
	public String getStorageId() {
		return this.storageId;
	}

	public void setStorageId(String storageId) {
		this.storageId = storageId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof InvoiceNoticeId))
			return false;
		InvoiceNoticeId castOther = (InvoiceNoticeId) other;

		return ((this.getInvoiceId() == castOther.getInvoiceId()) || (this.getInvoiceId() != null
				&& castOther.getInvoiceId() != null && this.getInvoiceId().equals(castOther.getInvoiceId())))
				&& ((this.getStorageId() == castOther.getStorageId()) || (this.getStorageId() != null
						&& castOther.getStorageId() != null && this.getStorageId().equals(castOther.getStorageId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getInvoiceId() == null ? 0 : this.getInvoiceId().hashCode());
		result = 37 * result + (getStorageId() == null ? 0 : this.getStorageId().hashCode());
		return result;
	}

}