
package com.smm.ctrm.domain.Physical;
// default package

// Generated 2016-4-20 21:35:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * LotBrandId generated by hbm2java
 */
@Embeddable
public class LotBrandId implements java.io.Serializable {

	@JsonProperty(value = "LotId")
	private String lotId;
	@JsonProperty(value = "BrandId")
	private String brandId;

	public LotBrandId() {
	}

	public LotBrandId(String lotId, String brandId) {
		this.lotId = lotId;
		this.brandId = brandId;
	}

	@Column(name = "LotId", nullable = false, length = 36)
	public String getLotId() {
		return this.lotId;
	}

	public void setLotId(String lotId) {
		this.lotId = lotId;
	}

	@Column(name = "BrandId", nullable = false, length = 36)
	public String getBrandId() {
		return this.brandId;
	}

	public void setBrandId(String brandId) {
		this.brandId = brandId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LotBrandId))
			return false;
		LotBrandId castOther = (LotBrandId) other;

		return ((this.getLotId() == castOther.getLotId()) || (this.getLotId() != null && castOther.getLotId() != null
				&& this.getLotId().equals(castOther.getLotId())))
				&& ((this.getBrandId() == castOther.getBrandId()) || (this.getBrandId() != null
						&& castOther.getBrandId() != null && this.getBrandId().equals(castOther.getBrandId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getLotId() == null ? 0 : this.getLotId().hashCode());
		result = 37 * result + (getBrandId() == null ? 0 : this.getBrandId().hashCode());
		return result;
	}

}