
package com.smm.ctrm.domain.Physical;
// default package

// Generated 2016-4-20 21:35:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * LotBrand generated by hbm2java
 */
@Entity
@Table(name = "LotBrand", schema = "Physical")
public class LotBrand implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private LotBrandId id;
	
	private Lot lot;

	public LotBrand() {
	}

	public LotBrand(LotBrandId id, Lot lot) {
		this.id = id;
		this.lot = lot;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "lotId", column = @Column(name = "LotId", nullable = false, length = 36)),
			@AttributeOverride(name = "brandId", column = @Column(name = "BrandId", nullable = false, length = 36)) })
	public LotBrandId getId() {
		return this.id;
	}

	public void setId(LotBrandId id) {
		this.id = id;
	}

	// @JsonBackReference("LotBrand_")
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "LotId", nullable = false, insertable = false, updatable = false)
	public Lot getLot() {
		return this.lot;
	}

	public void setLot(Lot lot) {
		this.lot = lot;
	}

}