
package com.smm.ctrm.domain.Physical;
// default package

// Generated 2016-4-20 21:35:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SummFeeStorage generated by hbm2java
 */
@Entity
@Table(name = "SummFeeStorage", schema = "Physical")
public class SummFeeStorage implements java.io.Serializable {

	private SummFeeStorageId id;
	private SummaryFees summaryFees;
	private Storage storage;

	public SummFeeStorage() {
	}

	public SummFeeStorage(SummFeeStorageId id, SummaryFees summaryFees, Storage storage) {
		this.id = id;
		this.summaryFees = summaryFees;
		this.storage = storage;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "storageId", column = @Column(name = "StorageId", nullable = false, length = 36)),
			@AttributeOverride(name = "summaryFeesId", column = @Column(name = "SummaryFeesId", nullable = false, length = 36)) })
	public SummFeeStorageId getId() {
		return this.id;
	}

	public void setId(SummFeeStorageId id) {
		this.id = id;
	}

	// @JsonBackReference("SummFeeStorage_")
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SummaryFeesId", nullable = false, insertable = false, updatable = false)
	public SummaryFees getSummaryFees() {
		return this.summaryFees;
	}

	public void setSummaryFees(SummaryFees summaryFees) {
		this.summaryFees = summaryFees;
	}

	// @JsonBackReference
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "StorageId", nullable = false, insertable = false, updatable = false)
	public Storage getStorage() {
		return this.storage;
	}

	public void setStorage(Storage storage) {
		this.storage = storage;
	}

}