
package com.smm.ctrm.domain.Physical;
// default package

// Generated 2016-4-20 21:35:22 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * SummFeeStorageId generated by hbm2java
 */
@Embeddable
public class SummFeeStorageId implements java.io.Serializable {

	@JsonProperty(value = "StorageId")
	private String storageId;
	@JsonProperty(value = "SummaryFeesId")
	private String summaryFeesId;

	public SummFeeStorageId() {
	}

	public SummFeeStorageId(String storageId, String summaryFeesId) {
		this.storageId = storageId;
		this.summaryFeesId = summaryFeesId;
	}

	@Column(name = "StorageId", nullable = false, length = 36)
	public String getStorageId() {
		return this.storageId;
	}

	public void setStorageId(String storageId) {
		this.storageId = storageId;
	}

	@Column(name = "SummaryFeesId", nullable = false, length = 36)
	public String getSummaryFeesId() {
		return this.summaryFeesId;
	}

	public void setSummaryFeesId(String summaryFeesId) {
		this.summaryFeesId = summaryFeesId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof SummFeeStorageId))
			return false;
		SummFeeStorageId castOther = (SummFeeStorageId) other;

		return ((this.getStorageId() == castOther.getStorageId()) || (this.getStorageId() != null
				&& castOther.getStorageId() != null && this.getStorageId().equals(castOther.getStorageId())))
				&& ((this.getSummaryFeesId() == castOther.getSummaryFeesId())
						|| (this.getSummaryFeesId() != null && castOther.getSummaryFeesId() != null
								&& this.getSummaryFeesId().equals(castOther.getSummaryFeesId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getStorageId() == null ? 0 : this.getStorageId().hashCode());
		result = 37 * result + (getSummaryFeesId() == null ? 0 : this.getSummaryFeesId().hashCode());
		return result;
	}

}